// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCByWDSPJ_AaPLVx_QW56cfhtPZOcvssrM',
    appId: '1:697023074939:web:cf3db64ca57a9c775788de',
    messagingSenderId: '697023074939',
    projectId: 'test-95160',
    authDomain: 'test-95160.firebaseapp.com',
    storageBucket: 'test-95160.appspot.com',
    measurementId: 'G-SHDC7S4FQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiY3CQlEfUcsKrd6I3vMWTZ-zGmCOJwiQ',
    appId: '1:697023074939:android:861da1993449cab15788de',
    messagingSenderId: '697023074939',
    projectId: 'test-95160',
    storageBucket: 'test-95160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrVeUnDc7CTSRf8xSmFP7fXzCMOJDb9s',
    appId: '1:697023074939:ios:c847781aa5ceeef65788de',
    messagingSenderId: '697023074939',
    projectId: 'test-95160',
    storageBucket: 'test-95160.appspot.com',
    iosBundleId: 'com.example.untitled17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyrVeUnDc7CTSRf8xSmFP7fXzCMOJDb9s',
    appId: '1:697023074939:ios:bb476040dd70307f5788de',
    messagingSenderId: '697023074939',
    projectId: 'test-95160',
    storageBucket: 'test-95160.appspot.com',
    iosBundleId: 'com.example.untitled17.RunnerTests',
  );
}
